pose:
  0
joints:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  active_home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  pre_pickup_cube:
    - 0.0
    - 0.25
    - 0.0
    - 0.99
    - 0
    - 1.85
    - 0

  pickup_cube:
    - -0.019
    - 0.183
    - 0.0
    - 1.67
    - 0.0
    - 1.28
    - 0.014

  pre_pickup_ball:
    - 0.0
    - -0.415
    - 0.0
    - -0.762
    - 0.0
    - -1.747
    - 0

  # Handoff 1
  pre_handoff:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  # Handoff 2
  handoff_2a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_2b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_2c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  # Handoff 3
  handoff_3a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  

  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0
  folding:
    step_0:
      - 0.0
      - -14.0
      - 10.0
      - 1.0
      - 5.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - -14.0
      - 50.0
      - 1.0
      - 20.0
      - -90.0
      - 0.0

    step_2:
      - 0.0
      - -14.0
      - 90.0
      - 1.0
      - 50.0
      - -175.0
      - 0.0

    step_3:
      - -5
      - -25.0
      - 100.0
      - 1.0
      - 50.0
      - -175.0
      - 0.0

    step_4:
      - -5
      - -25.0
      - 120.0
      - 1.0
      - 50.0
      - -175.0
      - 0.0

grip_pose:
  open: 2
  close: 0
  half_close: 0.5
  grasp_cube: 0.16