pose:
  0
joints:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  active_home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  pre_pickup_cube:
    - 0.0
    - 0.25
    - 0.0
    - 0.99
    - 0
    - 1.85
    - 0

  pickup_cube:
    - -0.019
    - 0.183
    - 0.0
    - 1.67
    - 0.0
    - 1.28
    - 0.014

  pre_pickup_ball:
    - 0.0
    - -0.415
    - 0.0
    - -0.762
    - 0.0
    - -1.747
    - 0

  # Handoff 1
  pre_handoff:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_1c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  # Handoff 2
  handoff_2a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_2b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_2c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  # Handoff 3
  handoff_3a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  


  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0
  folding:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0


#     step_0:
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0

#     step_1:
#       - 0.0
#       - 0.0 
#       - 0.0 
#       - 0.0 
#       - 0.0 
#       - 0.0 
#       - 0.0

#     step_3:
#       - 0.0
#       - 0.2443 
#       - 0.1745 
#       - 0.0174
#       - 0.0872
#       - 0.0
#       - 0.0

#     step_4:
#       - 0.0
#       - 0.2443
#       - 0.8726
#       - 0.0174
#       - 0.3490
#       - 1.5708
#       - 0.0

#     step_5:
#       - 0.0
#       - 0.2443
#       - 1.5708
#       - 0.0174
#       - 0.3490
#       - 3.1415
#       - 0.0

#     step_6:
#       - 0.3316
#       - 0.2443
#       - 2.0944
#       - 0.0174
#       - 0.8726
#       - 3.1415
#       - 0.0

#     step_7:
#       - 0.3316
#       - 1.5708
#       - 2.5307
#       - 0.0174
#       - 2.0944
#       - 3.1415
#       - 0.0

#     step_8:
#       - 0.3316
#       - 1.5708
#       - 3.4906
#       - 0.0174
#       - 0.0
#       - 3.1415
#       - 0.0

# # pickup object 1 poses
#   pickup_obj_1:
#     step_0:
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0


#     step_1:
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0
#       - 0.0


      # continue with the poses to pickup the first ball...

# pickup object 2 positions
  pickup_obj_2:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

      # continue with the poses to picup the second ball...

# positions for picking up the cube
  pickup_obj_3:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

      # continue with the poses to picup the first cube...

# throw object 2 movements
  throw_obj_1:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# throw object 2 movments 
  throw_obj_2:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# throw object 3 positions
  throw_obj_3:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# poses to yeet the objects
  discard_obj:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

grip_pose:
  open: 2
  close: 0
  half_close: 0.5
  grasp_cube: 0.16