pose:
  0
joints:
  open:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.07
    - 0.0
    - 0.0
    - 0.3

  close:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.5
    
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  active_home:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0

  pre_active_home:
    - 0.0
    - 1.2108
    - -1.6000
    - 3.187
    - 2.046
    - 0.0192
    - 0.0411

  pre_pickup_cube:
    - 0.0
    - 0.25
    - 0.0
    - 0.99
    - 0
    - 1.85
    - 0

  pickup_cube:
    - -0.019
    - 0.183
    - 0.0
    - 1.67
    - 0.0
    - 1.28
    - 0.014

  pre_pickup_ball:
    - 0.0
    - -0.415
    - 0.0
    - -0.762
    - 0.0
    - -1.747
    - 0

  # Handoff 1
  pre_handoff_1:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0      # same as active home

  handoff_1a:
    - -0.06
    - 1.440
    - -1.238
    - 2.7368
    - 2.0017
    - -0.2400
    - 1.6178
    - 0      # move to handoff position

  handoff_1b:
    - -0.06
    - 1.440
    - -1.238
    - 2.7368
    - 2.0017
    - -0.2400
    - 0.693
    - 0    # open gripper

  handoff_1c:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0      # move back to active home


  # Handoff 2
  pre_handoff_2:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0

  handoff_2a:
    - -0.1761
    - 1.5347
    - -1.4560
    - 2.7368
    - 2.344
    - -0.127
    - 0.7206
    - 0           # move toward the handoff position

  handoff_2b:
    - -0.06
    - 1.440
    - -1.238
    - 2.7368
    - 2.0017
    - -0.2400
    - 1.6178
    - 0           # handoff position with gripper open

  handoff_2c:
    - -0.06
    - 1.440
    - -1.238
    - 2.7368
    - 2.0017
    - -0.2400
    - 1.6178
    - 0           # handoff position with gripper closed

  handoff_2d:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0          # back home


  discard_0:
    - -0.1043
    - 1.5178
    - -1.286
    - 2.2866
    - 2.385
    - -1.115
    - 0.4152
    - 0.0

  # Handoff 3
  pre_handoff_3:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3d:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  
  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0

  # folding and unfolding
  # done-ish
  folding:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0
      - 0.3

    step_3:
      - 0.0
      - 0.2443 
      - -0.1745 
      - 0.0174
      - 0.0872
      - 0.0
      - 0.0
      - 0.4

    step_4:
      - -0.0500
      - 0.3309
      - -0.2139
      - 0.0004
      - 0.3045
      - 0.1422
      - 0.0
      - 0.5

    step_5:
      - 0.4633
      - 0.3316
      - -0.2016
      - 0.0004
      - 0.4888
      - 0.1450
      - 0.0
      - 0.0

    step_6:
      - -0.1909
      - 0.3309
      - -0.8415
      - 0.0004
      - 0.2330
      - 0.1450
      - 0.0
      - 0.0

    step_7:
      - -0.2484
      - 1.0407
      - -0.9664
      - 0.0004
      - -0.1240
      - 0.1450
      - 0.0
      - 0.0

    step_8:
      - 0.3000
      - 1.330
      - -0.9664
      - 0.0004
      - -0.1240
      - 0.1450
      - 0.0
      - 0.0

    step_9:
      - 0.3000
      - 1.330
      - -0.9664
      - 0.0004
      - 2.200
      - 0.1450
      - 0.0
      - 0.0

    

# pickup object 1 poses
# done-ish
  pickup_obj_1:
    step_0:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 15

    step_1:
    - -0.07
    - 1.169
    - -1.470
    - 3.152
    - 1.99
    - -0.1789
    - 0.19
    - 15

    step_2:
    - -0.00
    - 1.165
    - -1.25
    - 3.265
    - 2.09
    - -0.299
    - 0.0332
    - 15

    step_3:
    - -0.00
    - 1.35
    - -1.35
    - 3.234
    - 2.286
    - -0.280
    - 0.0969
    - 15

    step_4:
    - -0.02
    - 1.35
    - -1.68
    - 3.22
    - 2.267
    - -0.308
    - 0.140
    - 15

    step_5:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 15

      # continue with the poses to pickup the first ball...

# pickup object 2 positions
  pickup_obj_2:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

      # continue with the poses to picup the second ball...

# positions for picking up the cube
  pickup_obj_3:
    step_0:
      - -0.22
      - 1.535
      - -1.4989
      - 2.7457
      - 2.2593
      - -0.315
      - 0.44
      - 0.0

    step_1:
      - -0.07
      - 1.169
      - -1.470
      - 3.152
      - 1.99
      - -0.1789
      - 0.19
      - 0.0

    step_2:
      - -0.00
      - 1.165
      - -1.25
      - 3.265
      - 2.09
      - -0.299
      - 0.0332
      - 0.0

    step_3:
      - -0.00
      - 1.35
      - -1.35
      - 3.234
      - 2.286
      - -0.280
      - 0.0969
      - 0.0

    step_4:
      - -0.02
      - 1.35
      - -1.68
      - 3.22
      - 2.267
      - -0.308
      - 0.140
      - 0.0

    step_5:
      - -0.22
      - 1.535
      - -1.4989
      - 2.7457
      - 2.2593
      - -0.315
      - 0.44
      - 0.0

      # continue with the poses to picup the first cube...

# throw object 2 movements
  throw_obj_1:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# throw object 2 movments 
  throw_obj_2:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# throw object 3 positions
  throw_obj_3:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# poses to yeet the objects
  discard_obj:
    step_0:
      - -0.1043
      - 1.5178
      - -1.286
      - 2.2866
      - 2.385
      - -1.115
      - 04152
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_2:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

grip_pose:
  open: 2
  close: 0
  half_close: 0.5
  grasp_cube: 0.16