pose:
  0
joints:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  pre_pickup_wrench:
    - 0.17
    - -1.55
    - 1.056
    - 1.106
    - -3.13
    - -1.83
    - -1.21

  pickup_wrench:
    - 0.145
    - -1.55
    - 1.055
    - 1.51
    - -3.141
    - -1.43
    - -1.21

  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0
  folding:
    step_0:
      - 1.0
      - 0.85
      - 0.677
      - 1.23
      - 0.86
      - 1.82
      - -0.46

    step_1:
      - 0.169
      - 0.806
      - 0.905
      - 1.51
      - 1.268
      - 0.807
      - -0.624

    step_2:
      - 0.12
      - 1.49
      - -7.73
      - -0.41
      - -6.44
      - -1.79
      - -3.13

grip_pose:
  open: 1
  close: -1
  half_close: -0.5
  grasp_cube: -0.84