pose:
  0
joints:
  open:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.05
    - 0.0
    - 0.0
    - 0.25

  close:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.5

  move_home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  pre_pickup_wrench:
    - 1.254
    - 0.595
    - 1.46
    - -0.367
    - -0.444
    - 1.187
    - -0.771

  pickup_wrench:
    - 1.195
    - -0.149
    - 1.115
    - 0.154
    - 0.249
    - 1.42
    - -0.771

  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0
  folding:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.2  # open gripper

    step_1:
      - 0.3681   # this one moves here to compensate for the movmenet of j3
      - 0.0
      - 0.371
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.2  # open gripper    

    step_2:
      - 0.3681   # this one moves here 
      - -0.3
      - 0.371
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.5    # move back and away from 

    step_3:
      - 0.3681 
      - -0.35
      - 0.371
      - 0.0
      - -0.1
      - 0.0
      - 0.0
      - 0.85

    step_4:
      - 0.3681
      - -0.30
      - 0.422
      - 0.11
      - 0.3781
      - 0.0
      - -0.2563
      - 0.85

    step_5:
      - 0.3681
      - -0.0
      - 1.223
      - 0.0965
      - 0.7403
      - -1.665
      - -0.310 
      - 0.0

    step_6:
      - -0.3431
      - -0.175
      - 1.737
      - -0.0546
      - 0.904
      - -3.10
      - -0.540
      - 0.0

    step_7:
      - -0.2122
      - -0.4
      - 2.04
      - -0.0546
      - 1.16
      - -3.10
      - -0.7090
      - 0.0

    step_8:
      - 0.305
      - -0.4
      - 2.04
      - -0.0546
      - 1.16
      - -3.10
      - -0.7090
      - 0.0

    step_9:
      - 0.360
      - -0.4
      - 2.5666
      - -0.0546
      - 1.16
      - -3.0
      - -0.7090
      - 0.0

    step_10:
      - 0.386
      - -0.849
      - 2.6866
      - -0.0546
      - 1.64
      - -3.0
      - -0.824 
      - 0.0

    step_11:
      - 0.386
      - -1.500
      - 2.917 
      - -0.0546
      - 1.809
      - -3.10
      - -0.874
      - 0.0

    step_12:
      - 0.386
      - -1.500
      - 2.917
      - -0.0546
      - -0.7787
      - -3.10
      - -0.874
      - 0.0

    step_13:
      - 0.279
      - -1.540
      - -0.374
      - 1.654  
      - 2.337  
      - -1.64
      - -0.651
      - 0.0

  active_home:
    - 0.2117
    - -1.7003
    - 0.1075
    - 0.9145
    - 2.2619
    - -3.1279
    - 3.8327
    - 0.0

  pre_handoff:
    - 0.2117
    - -1.7003
    - 0.1075
    - 0.9145
    - 2.2619
    - -3.1279
    - 3.8327
    - 1

  handoff_1a:
    - 0.1750
    - -1.700
    - 0.068
    - 0.3978
    - 2.421
    - -2.722
    - 3.809
    - 1

  handoff_1b:
    - 0.1750
    - -1.700
    - 0.068
    - 0.3978
    - 2.421
    - -2.722
    - 3.809
    - 0.25

  handoff_1c:
    - 0.2894
    - -1.7
    - 0.093
    - 0.5517
    - 2.422
    - -3.0
    - 4.465
    - 0

#discard
  discard_obj_1a:
    - 0.284
    - -1.7
    - -0.13
    - 0.769
    - 2.44
    - -1.88
    - 3.809
    - 0

  discard_obj_1b:
    - 0.284
    - -1.7
    - -0.362
    - 0.783
    - 2.53
    - -1.06
    - 3.809
    - 1

#pickup object 2
  pickup_obj_2:
    step_0:
      - 0.1133
      - -1.7
      - 0.03
      - 0.1722
      - 2.815
      - -2.719
      - 3.143 
      - 0.5

    step_1:
      - 0.05
      - -1.7
      - -0.023
      - 0.12
      - 2.70 
      - -2.756
      - 3.205
      - 0.6

    step_2:
      - -0.1 
      - -1.7
      - -0.26
      - 0.13
      - 2.54
      - -2.85 
      - 3.67
      - 0.6

    step_3:
      - -0.1 
      - -1.7
      - -0.26
      - 0.13
      - 2.54
      - -2.85 
      - 3.524
      - 0.1

    step_4:
      - -0.04
      - -1.7
      - -0.25
      - 0.13
      - 2.648
      - -2.86
      - 3.522
      - 0.1

    step_5:
      - -0.04
      - -1.7
      - -0.25
      - 0.129
      - 3.009
      - -2.92
      - 3.414
      - 0.0

    step_6:
      - -0.04
      - -1.7
      - -0.25
      - 0.129
      - 3.090
      - -2.68
      - 3.583
      - 0.0

# handoff 2

  pre_handoff_give:
    - 0.14
    - -1.7
    - -0.077
    - 0.533
    - 2.46
    - -2.810
    - 3.244
    - 0

  handoff_2a:
    - 0.08 
    - -1.7
    - -0.113
    - 0.3593
    - 2.711
    - -2.509
    - 3.247
    - 0

  handoff_2b:
    - 0.08 
    - -1.7
    - -0.113
    - 0.3593
    - 2.711
    - -2.509
    - 3.247
    - 1

  handoff_2c:
    - 0.1750
    - -1.700
    - 0.068
    - 0.3978
    - 2.421
    - -2.722
    - 3.809
    - 1

  pickup_obj_1:
    - 0.0

  pickup_obj_3:
    - 0.0

  discard_obj:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

grip_pose:
  open: 2
  close: 0
  half_close: 0.5
  grasp_cube: 0.16