pose:
  0
joints:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  pre_pickup_wrench:
    - 0.17
    - -1.55
    - 1.056
    - 1.106
    - -3.13
    - -1.83
    - -1.21

  pickup_wrench:
    - 0.145
    - -1.55
    - 1.055
    - 1.51
    - -3.141
    - -1.43
    - -1.21

grip_pose:
  open: 1
  close: -1
  half_close: -0.5
  grasp_cube: -0.84