pose:
  0
joints:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  pre_pickup_wrench:
    - 1.254
    - 0.595
    - 1.46
    - -0.367
    - -0.444
    - 1.187
    - -0.771

  pickup_wrench:
    - 1.195
    - -0.149
    - 1.115
    - 0.154
    - 0.249
    - 1.42
    - -0.771

  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0
  folding:
    step_0:
      - 1.276
      - 0.94
      - 1.605
      - -0.387
      - -0.40
      - 0.83
      - -0.80

    step_1:
      - 1.259
      - 0.97
      - 1.57
      - 1.26
      - -0.409
      - 0.69
      - 0.82

    step_2:
      - 0.761
      - 0.313
      - 3.08
      - -0.17
      - -0.36
      - 0.72
      - -0.86

    step_3:
      - -0.174
      - -1.322
      - 3.07
      - 1.566
      - -0.36
      - 1.92
      - 0.85

    step_4:
      - -0.173
      - -1.32
      - 3.07
      - 1.59
      - 0.0
      - 2.75
      - 0.85

grip_pose:
  open: 2
  close: 0
  half_close: 0.5
  grasp_cube: 0.16