arm2d2/controllers:
  state:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  velocity:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    gains:
      joint_1: {p: 30,  d: 0, i: 0.0001, i_clamp: 1}
      joint_2: {p: 20,  d: 0, i: 0.0001, i_clamp: 1}
      joint_3: {p: 10,  d: 0.01, i: 0.0001, i_clamp: 1}
      joint_4: {p: 30,  d: 0, i: 0.0001, i_clamp: 1}
      joint_5: {p: 15,  d: 0, i: 0.001, i_clamp: 1}
      joint_6: {p: 6, d: 0.7, i: 0.00001, i_clamp: 1}
      joint_7: {p: 7, d: 0.9, i: 0.0001, i_clamp: 1}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1
      joint_1:
        trajectory: 0.2
        goal: 0.1
      joint_2:
        trajectory: 0.2
        goal: 0.1
      joint_3:
        trajectory: 0.2
        goal: 0.1
      joint_4:
        trajectory: 0.2
        goal: 0.1
      joint_5:
        trajectory: 0.2
        goal: 0.1
      joint_6:
        trajectory: 0.2
        goal: 0.1
      joint_7:
        trajectory: 0.2
        goal: 0.1

  grip_position:
    type: "position_controllers/JointPositionController"
    joint: gripper_actuator

  position:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

    constraints:
      goal_time: 0.6
      joint_1:
          trajectory: 0.2
          goal: 0.1
      joint_2:
          trajectory: 0.2
          goal: 0.1
      joint_3:
          trajectory: 0.2
          goal: 0.1
      joint_4:
          trajectory: 0.2
          goal: 0.1
      joint_5:
          trajectory: 0.2
          goal: 0.1