stepper_config:
  num_joints: 11
  num_grip_joints: 4
  joint_names:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - gripper_joint_1
    - gripper_joint_2
    - gripper_joint_3
    - gripper_joint_4
  deg_per_step:
    - 1.8
    - 1.8
    - 1.8
    - 1.8
    - 1.8
    - 1.8
    - 1.8
  deg_per_enc_step:
    - 0.008333
    - 1.8
    - 1.8
    - 1.8
    - 1.8
    - 1.8
    - 1.8
  gripper_gain: 50