stepper_config:
  num_joints: 11
  num_grip_joints: 4
  joint_names:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - gripper_joint_1
    - gripper_joint_2
    - gripper_joint_3
    - gripper_joint_4
  deg_per_step:
  # current values are estimates
    - 0.0225 #0.09    # 360 / 4000
    - 0.0128 #0.018   # 5000 / 90
    - 0.0134 #0.036   # 90 / 2500
    - 0.1 #0.3     # 90 / 300
    - 0.1 #0.3     # 90 / 300
  gripper_gain: 50
  gains:
    joint_1: {p: 60,  d: 0, i: 0.01, i_clamp: 1}
    joint_2: {p: 65,  d: 0, i: 0.1, i_clamp: 1}
    joint_3: {p: 40,  d: 0, i: 0.1, i_clamp: 1} # Good!
    joint_4: {p: 65,  d: 0, i: 0.01, i_clamp: 1}
    joint_5: {p: 40,  d: 0, i: 0.001, i_clamp: 1} # Good!
    joint_6: {p: 60, d: 0.1, i: 0.05, i_clamp: 1}
    joint_7: {p: 45, d: 0.1, i: 0.01, i_clamp: 1}
  goal_position_accuracy: 0.1
  max_goal_time: 10 # in seconds