pose:
  post_throw:
    position:
      x: -0.003
      y: 0.23
      z: 0.132
    orientation:
      x: 0.0215694
      y: 0.702411
      z: 0.00727993
      w: 0.711407


joints:
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  test:
    - 2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  test2:
    - -2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  
  pre_pickup:
    - 0.663
    - -0.11
    - -0.419
    - 0
    - 0.45
    - 0

  pickup:
    - 0.68
    - 0
    - -0.125
    - 0.017
    - 0.017
    - 0

grip_pose:
  open: 1
  close: -0.1
  half_close: 0.5