stepper_config:
  num_joints: 4
  num_grip_joints: 4
  joint_names:
    - gripper_joint_1
    - gripper_joint_2
    - gripper_joint_3
    - gripper_joint_4
  gripper_gain: 50
  deg_per_step:
  # current values are estimates
    - 0.0225 #0.09    # 360 / 4000
    - 0.0128 #0.018   # 5000 / 90
    - 0.0134 #0.036   # 90 / 2500
    - 0.1 #0.3     # 90 / 300
    - 0.1 #0.3     # 90 / 300