TrajectoryPredictorConfig:
    # Kalman Filters
    acceleration_variance: 0.5
    measurement_variance: 0.5
    initial_uncertainty_guess: 10

    # Trajectory search
    arm_length: 1
    robot_base:
      - 0
      - 0
      - 0
    sufficient_convergence: 0.001
    search_delta: 0.01

    min_time_delta: 0.05
    max_time_delta: 5
    
